import type { Library } from "./types";

export const SEED_LIBRARY: Library = {
  profile: {
    name: "Jordan Hale",
    contact: "text 555-0148 · @jordansshelf",
    city: "Austin, TX",
    note: "Physical PS5 copies only. Local pickup preferred. Discs pictured are the copies you get.",
  },
  games: [
    {
      id: "astro-bot",
      title: "Astro Bot",
      platform: "PS5",
      purchasePrice: 59.99,
      purchaseDate: "2024-09-12",
      askingPrice: null,
      soldPrice: null,
      status: "completed_still_playing",
      condition: "mint",
      notes: "Platinum'd the main path. Still hopping back in for the extra levels.",
      coverColor: "#3b82f6",
      coverImage: null,
      discPhoto: null,
      loans: [
        {
          id: "loan-ab-1",
          person: "Priya",
          date: "2025-01-18",
          amount: 10,
          note: "Weekend borrow, cash",
          returned: true,
        },
      ],
    },
    {
      id: "spider-man-2",
      title: "Marvel's Spider-Man 2",
      platform: "PS5",
      purchasePrice: 69.99,
      purchaseDate: "2023-10-20",
      askingPrice: 35,
      soldPrice: null,
      status: "for_sale",
      condition: "near_mint",
      notes: "Case and disc clean. Includes original insert.",
      coverColor: "#dc2626",
      coverImage: null,
      discPhoto: null,
      loans: [
        {
          id: "loan-sm-1",
          person: "Marcus",
          date: "2024-06-02",
          amount: 15,
          note: "Two-week loan",
          returned: true,
        },
        {
          id: "loan-sm-2",
          person: "Ava",
          date: "2025-03-11",
          amount: 12,
          note: "Traded for gas money on a trip",
          returned: true,
        },
      ],
    },
    {
      id: "ff16",
      title: "Final Fantasy XVI",
      platform: "PS5",
      purchasePrice: 69.99,
      purchaseDate: "2023-06-22",
      askingPrice: null,
      soldPrice: null,
      status: "in_progress",
      condition: "good",
      notes: "Mid-game. Disc has a faint scuff that does not affect play.",
      coverColor: "#7c3aed",
      coverImage: null,
      discPhoto: null,
      loans: [],
    },
    {
      id: "god-of-war",
      title: "God of War Ragnarök",
      platform: "PS5",
      purchasePrice: 49.99,
      purchaseDate: "2022-11-09",
      askingPrice: null,
      soldPrice: 30,
      status: "sold",
      condition: "good",
      notes: "Sold to a coworker after finishing the story.",
      coverColor: "#0ea5e9",
      coverImage: null,
      discPhoto: null,
      loans: [
        {
          id: "loan-gow-1",
          person: "Chris",
          date: "2023-08-04",
          amount: 20,
          note: "Month-long borrow before they bought their own",
          returned: true,
        },
      ],
    },
    {
      id: "re4",
      title: "Resident Evil 4",
      platform: "PS5",
      purchasePrice: 39.99,
      purchaseDate: "2024-02-14",
      askingPrice: null,
      soldPrice: null,
      status: "lent_out",
      condition: "near_mint",
      notes: "Currently with Devon. Due back next Friday.",
      coverColor: "#b45309",
      coverImage: null,
      discPhoto: null,
      loans: [
        {
          id: "loan-re-1",
          person: "Devon",
          date: "2026-09-05",
          amount: 8,
          note: "Open loan — still out",
          returned: false,
        },
      ],
    },
    {
      id: "returnal",
      title: "Returnal",
      platform: "PS5",
      purchasePrice: 29.99,
      purchaseDate: "2025-05-03",
      askingPrice: null,
      soldPrice: null,
      status: "completed",
      condition: "mint",
      notes: "Finished the story. Sitting on the shelf until the next NG+ itch.",
      coverColor: "#059669",
      coverImage: null,
      discPhoto: null,
      loans: [],
    },
    {
      id: "demon-souls",
      title: "Demon's Souls",
      platform: "PS5",
      purchasePrice: 44.99,
      purchaseDate: "2024-11-28",
      askingPrice: 28,
      soldPrice: null,
      status: "for_sale",
      condition: "mint",
      notes: "Launch-style reprint. No DLC to worry about — this is the full disc.",
      coverColor: "#eab308",
      coverImage: null,
      discPhoto: null,
      loans: [],
    },
    {
      id: "stellar-blade",
      title: "Stellar Blade",
      platform: "PS5",
      purchasePrice: 69.99,
      purchaseDate: "2024-04-26",
      askingPrice: null,
      soldPrice: null,
      status: "on_shelf",
      condition: "mint",
      notes: "Bought on a trade night. Haven't cracked it yet.",
      coverColor: "#ec4899",
      coverImage: null,
      discPhoto: null,
      loans: [],
    },
  ],
};
